FROM nginx:1.25.1

#el nginx lo metemos a este folder y tambien metemos la carpeta  al contenedor
#    esta carpeta al contenedor
#aca traemos el html y lo agregamos al contenedor para que se abra junto con el contendor
#si hacemos cambios en el index necestiamos hacer un build y correr de nuevo
COPY static  /usr/share/nginx/html